### ISSUE TITLE
BPF

### ISSUE THREAD

**Issue by mgaulton** [jasonish/docker-snort#1]
I'm not sure where i might add the option to ignore the local networks (node to node) and only concentray on the inbounce internet traffic.

Where would I add a BPF or what format of a rule might i add to the white_list.rules?

**Comment by jasonish** [comment]
Have you thought about using HOME_NET?  I just updated the image to Snort 2.9.7.6 and made some other changes.  If you use the launcher script, the snort.conf will end up in ./data/etc/snort/snort.conf - here you can set your HOME_NET then start Snort like:

    launcher run snort -c /data/etc/snort/snort.conf

I'm not that familiar with white_list.rules myself.

**Comment by mgaulton** [comment]
sounds good. let me try that. I'm not familiar either but it appeared to be what some people were recommending.

**Comment by mehmetcodes** [comment]
2.9.7.6 is end of life
http://blog.snort.org/2017/03/snort-2976-is-end-of-life.html
