### ISSUE TITLE
QQ: interface

### ISSUE THREAD

**Issue by mgaulton** [jasonish/docker-snort#2]
How did you make it listen to the hardware interface? maybe i'm missing something.

**Comment by jasonish** [comment]
Are you using the launcher script are starting the container manually?  The launcher script already does -net=host which should make the hardware interfaces visible inside the container.

One thought, if you have selinux enabled, --privileged might need to be provided as well, in fact I'm sure it does and this launcher script doesn't do that that.  I'll have to tweak that. 

In fact, I've been moving away from launcher scripts and just providing the documentation on how to start it manually with docker, as there is no way to provide a launcher script that satisfies all users.

**Comment by mgaulton** [comment]
Sounds good. the net=host is what I was missing. Thank you.

I'm a fan, keep up the good work
